RCIAM-343_getCous_query_in_attrauthcomanage_is_not_working_properly
rciam/simplesamlphp-module-attrauthcomanage pull request #20
Opened 2020-09-09 14:43 UTC by ioigoume

- Fetch COPerson memberships in one query.
- Fix wrong calculation of entitlements if the user is an admin but has no affiliation in a COU.

2020-09-13 05:44 UTC, ioigoume commented
@NicolasLiampotis please review

2020-09-14 11:32 UTC, NicolasLiampotis requested changes
Need to revert changes that break PSR-2 (or its newer PSR-12) which is part of the [contributing guidelines](https://github.com/simplesamlphp/simplesamlphp/blob/master/CONTRIBUTING.md)

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if($group['member'] === true) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if($group['owner'] === true) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if(!array_key_exists('eduPersonEntitlement', $state['Attributes'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +                if($this->urnLegacy) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +    private function _showException($e) {
Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body. (see https://www.php-fig.org/psr/psr-2/#1-overview)

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +    public function __construct($config, $reserved) {
Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body. (see https://www.php-fig.org/psr/psr-2/#1-overview)

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +        if(!array_key_exists('coId', $config)) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +        if(!is_int($config['coId'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +        if(!array_key_exists('urnNamespace', $config) && !is_string($config['urnNamespace'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +        if(!array_key_exists('voRoles', $config) && !is_string($config['voRoles'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +        if(!array_key_exists('urnAuthority', $config) && !is_string($config['urnAuthority'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +        if(!array_key_exists('registryUrls', $config)) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +          if(!empty($invalid_keys) || !empty($invalid_urls)) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +        if(array_key_exists('coUserIdType', $config)) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if(!is_string($config['coUserIdType'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +        if(array_key_exists('userIdAttribute', $config)) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if(!is_string($config['userIdAttribute'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if(!is_array($config['blacklist'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if(!is_array($config['voWhitelist'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if(!is_array($config['communityIdps'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if(!is_bool($config['urnLegacy'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +          if(!is_bool($config['urnLegacy'])) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +            if(isset($state['SPMetadata']['entityid']) && in_array($state['SPMetadata']['entityid'], $this->blacklist, true)) {
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else

2020-09-14 11:32 UTC, NicolasLiampotis commented on lib/Auth/Process/COmanageDbClient.php
> +    public function process(&$state) {
Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body. (see https://www.php-fig.org/psr/psr-2/#1-overview)

2020-09-14 14:40 UTC, ioigoume commented
Done with refactoring

2020-09-14 14:41 UTC, ioigoume commented on lib/Auth/Process/COmanageDbClient.php
> +            if(isset($state['SPMetadata']['entityid']) && in_array($state['SPMetadata']['entityid'], $this->blacklist, true)) {
Done

2020-09-14 14:42 UTC, ioigoume commented on lib/Auth/Process/COmanageDbClient.php
> +          if(!is_bool($config['urnLegacy'])) {
Done

2020-09-14 21:48 UTC, NicolasLiampotis approved these changes
LGTM

2020-09-14 21:49 UTC, merged