Enable job functionality for comanage (orgIdentity)
rciam/simplesamlphp-module-attrauthcomanage pull request #74
Opened 2022-03-30 06:17 UTC by lionick

minor fix

2022-03-30 07:12 UTC, ioigoume requested changes

2022-03-30 07:12 UTC, ioigoume commented on lib/Auth/Process/COmanageDbClient.php
> +        $this->orgIdentity = new User\OrgIdentity(null);
Do not pass null. Set the default null value to constructor parameter.

2022-03-30 08:01 UTC, ioigoume approved these changes
lgtm

2022-04-05 07:42 UTC, NicolasLiampotis approved these changes
LGTM

2022-04-05 07:42 UTC, merged